//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileHoome.Insure.ExtService.AegisRental {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aegisfirst.com/ws", ConfigurationName="AegisRental.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Parameter 'GetAstecDocumentResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/GetAstecDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentResponse GetAstecDocument(MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/GetAstecDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentResponse> GetAstecDocumentAsync(MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/GetAppointedAgents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAppointedAgents(string apiKey, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/GetAppointedAgents", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAppointedAgentsAsync(string apiKey, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/BlindQuotePolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void BlindQuotePolicy(string apiKey, System.Xml.XmlNode input, string productCode, MobileHoome.Insure.ExtService.AegisRental.AstecProcessingMode mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/BlindQuotePolicy", ReplyAction="*")]
        System.Threading.Tasks.Task BlindQuotePolicyAsync(string apiKey, System.Xml.XmlNode input, string productCode, MobileHoome.Insure.ExtService.AegisRental.AstecProcessingMode mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/QuotePolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode QuotePolicy(string apiKey, System.Xml.XmlNode input, string productCode, MobileHoome.Insure.ExtService.AegisRental.AstecProcessingMode mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/QuotePolicy", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> QuotePolicyAsync(string apiKey, System.Xml.XmlNode input, string productCode, MobileHoome.Insure.ExtService.AegisRental.AstecProcessingMode mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/AstecQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AstecQuery(string apiKey, string query, string formName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aegisfirst.com/ws/AstecQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AstecQueryAsync(string apiKey, string query, string formName);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAstecDocument", WrapperNamespace="http://aegisfirst.com/ws", IsWrapped=true)]
    public partial class GetAstecDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aegisfirst.com/ws", Order=0)]
        public string apiKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aegisfirst.com/ws", Order=1)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aegisfirst.com/ws", Order=2)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aegisfirst.com/ws", Order=3)]
        public string policy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aegisfirst.com/ws", Order=4)]
        public string endonumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aegisfirst.com/ws", Order=5)]
        public string report_type;
        
        public GetAstecDocumentRequest() {
        }
        
        public GetAstecDocumentRequest(string apiKey, string state, string company, string policy, string endonumber, string report_type) {
            this.apiKey = apiKey;
            this.state = state;
            this.company = company;
            this.policy = policy;
            this.endonumber = endonumber;
            this.report_type = report_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAstecDocumentResponse", WrapperNamespace="http://aegisfirst.com/ws", IsWrapped=true)]
    public partial class GetAstecDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aegisfirst.com/ws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetAstecDocumentResult;
        
        public GetAstecDocumentResponse() {
        }
        
        public GetAstecDocumentResponse(byte[] GetAstecDocumentResult) {
            this.GetAstecDocumentResult = GetAstecDocumentResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aegisfirst.com/ws")]
    public enum AstecProcessingMode {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        QuoteOverride,
        
        /// <remarks/>
        SubmitOverride,
        
        /// <remarks/>
        IssueOverride,
        
        /// <remarks/>
        RemitOverride,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : MobileHoome.Insure.ExtService.AegisRental.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<MobileHoome.Insure.ExtService.AegisRental.ServiceSoap>, MobileHoome.Insure.ExtService.AegisRental.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentResponse MobileHoome.Insure.ExtService.AegisRental.ServiceSoap.GetAstecDocument(MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentRequest request) {
            return base.Channel.GetAstecDocument(request);
        }
        
        public byte[] GetAstecDocument(string apiKey, string state, string company, string policy, string endonumber, string report_type) {
            MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentRequest inValue = new MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentRequest();
            inValue.apiKey = apiKey;
            inValue.state = state;
            inValue.company = company;
            inValue.policy = policy;
            inValue.endonumber = endonumber;
            inValue.report_type = report_type;
            MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentResponse retVal = ((MobileHoome.Insure.ExtService.AegisRental.ServiceSoap)(this)).GetAstecDocument(inValue);
            return retVal.GetAstecDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentResponse> MobileHoome.Insure.ExtService.AegisRental.ServiceSoap.GetAstecDocumentAsync(MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentRequest request) {
            return base.Channel.GetAstecDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentResponse> GetAstecDocumentAsync(string apiKey, string state, string company, string policy, string endonumber, string report_type) {
            MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentRequest inValue = new MobileHoome.Insure.ExtService.AegisRental.GetAstecDocumentRequest();
            inValue.apiKey = apiKey;
            inValue.state = state;
            inValue.company = company;
            inValue.policy = policy;
            inValue.endonumber = endonumber;
            inValue.report_type = report_type;
            return ((MobileHoome.Insure.ExtService.AegisRental.ServiceSoap)(this)).GetAstecDocumentAsync(inValue);
        }
        
        public System.Xml.XmlNode GetAppointedAgents(string apiKey, int agentId) {
            return base.Channel.GetAppointedAgents(apiKey, agentId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAppointedAgentsAsync(string apiKey, int agentId) {
            return base.Channel.GetAppointedAgentsAsync(apiKey, agentId);
        }
        
        public void BlindQuotePolicy(string apiKey, System.Xml.XmlNode input, string productCode, MobileHoome.Insure.ExtService.AegisRental.AstecProcessingMode mode) {
            base.Channel.BlindQuotePolicy(apiKey, input, productCode, mode);
        }
        
        public System.Threading.Tasks.Task BlindQuotePolicyAsync(string apiKey, System.Xml.XmlNode input, string productCode, MobileHoome.Insure.ExtService.AegisRental.AstecProcessingMode mode) {
            return base.Channel.BlindQuotePolicyAsync(apiKey, input, productCode, mode);
        }
        
        public System.Xml.XmlNode QuotePolicy(string apiKey, System.Xml.XmlNode input, string productCode, MobileHoome.Insure.ExtService.AegisRental.AstecProcessingMode mode) {
            return base.Channel.QuotePolicy(apiKey, input, productCode, mode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> QuotePolicyAsync(string apiKey, System.Xml.XmlNode input, string productCode, MobileHoome.Insure.ExtService.AegisRental.AstecProcessingMode mode) {
            return base.Channel.QuotePolicyAsync(apiKey, input, productCode, mode);
        }
        
        public System.Data.DataSet AstecQuery(string apiKey, string query, string formName) {
            return base.Channel.AstecQuery(apiKey, query, formName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AstecQueryAsync(string apiKey, string query, string formName) {
            return base.Channel.AstecQueryAsync(apiKey, query, formName);
        }
    }
}
